
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-analyzer
  labels:
    app: text-analyzer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: text-analyzer
  template:
    metadata:
      labels:
        app: text-analyzer
    spec:
      containers:
      - name: text-analyzer
        image: siddartha1192/text-analyser:latst
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: text-analyzer-service
spec:
  selector:
    app: text-analyzer
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30000
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: text-analyzer-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: text-analyzer
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
